export const DEFAULT = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis vitae nisi eu ante vestibulum scelerisque a ut risus. Pellentesque odio lacus, tempor nec tempus sit amet, lobortis sit amet nisl. Maecenas sit amet lorem blandit, tristique enim ut, rhoncus felis. Phasellus eros risus, ullamcorper elementum consectetur in, facilisis in ligula. Etiam fermentum dapibus finibus. Suspendisse ut diam eleifend, finibus arcu a, congue justo. Maecenas sollicitudin, tellus vitae porttitor dignissim, magna neque porta dui, ut porta tortor elit sit amet velit. Phasellus consectetur nibh eu libero porttitor scelerisque. Aenean eu odio ipsum. Vestibulum accumsan mattis tincidunt. Donec sed finibus elit. Aenean et urna magna.

Morbi at dictum risus. Vivamus vestibulum, tellus vel ornare porttitor, est libero pharetra erat, imperdiet imperdiet mi quam sit amet magna. Maecenas venenatis sit amet risus sit amet viverra. Nulla tincidunt efficitur risus quis iaculis. Praesent iaculis vel ex eu efficitur. Phasellus mattis sodales commodo. Nunc sit amet pulvinar erat. Sed feugiat risus nec justo dignissim maximus vitae sagittis nibh. Suspendisse blandit nunc vitae justo porttitor, et fringilla enim sagittis. Praesent vitae posuere odio. Mauris efficitur mi ipsum, sed mollis ex auctor eget. Etiam non cursus urna. Aenean ligula elit, rutrum eu urna eu, aliquet consectetur ligula. Integer luctus commodo augue vel feugiat. Mauris magna sem, imperdiet quis commodo ac, ullamcorper a justo.

Etiam vitae ex sagittis erat condimentum ultricies. Mauris non lectus nulla. Duis eget purus mattis, lacinia elit ut, sollicitudin velit. Duis quis mauris egestas, tincidunt arcu ut, feugiat tortor. Quisque nec dapibus est. Donec sed pulvinar nibh. Maecenas tempus placerat libero eget vehicula. Quisque dolor arcu, vestibulum sit amet tincidunt vitae, consequat sit amet lectus. Nam eu orci vitae mi tempor ultricies.

Phasellus eu tellus non tortor aliquam dignissim. Cras ornare augue sit amet volutpat cursus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis hendrerit in quam eget porta. Pellentesque placerat nec nunc non condimentum. Nunc sagittis augue vel felis congue scelerisque. Suspendisse mollis ultricies elit, non rutrum dolor ultricies sit amet.

Curabitur id urna eu nisl iaculis convallis. Quisque at congue nibh. Integer nec sapien lacus. Nullam eu mauris quam. Maecenas et ligula sit amet erat congue ornare. Proin lacinia turpis id est pharetra blandit. Proin sed lacus placerat, auctor erat ut, ultricies quam. Mauris sit amet gravida mauris.`;
